# Generated by Django 6.0.3 on 2026-05-04 22:12

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.CharField(help_text='Endereço de e-mail', max_length=100, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='fone',
            field=models.CharField(help_text='Número do telefone', max_length=15, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='pessoas', variations={}, verbose_name='Foto'),
        ),
    ]
