# Generated by Django 4.2.30 on 2026-05-05 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o nome do produto', max_length=30, unique=True, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço do produto', max_digits=5, verbose_name='Preço')),
                ('quantidade', models.DecimalField(decimal_places=2, help_text='Quantidade do produto', max_digits=5, verbose_name='Quantidade')),
                ('fornecedor', models.ForeignKey(help_text='Nome do fornecedor', on_delete=django.db.models.deletion.PROTECT, related_name='fornecedor', to='fornecedores.fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'produtos',
            },
        ),
    ]
