# Generated by Django 6.0.3 on 2026-04-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'produtos'},
        ),
        migrations.RemoveField(
            model_name='produto',
            name='name',
        ),
        migrations.AddField(
            model_name='produto',
            name='nome',
            field=models.CharField(default=1, help_text='Digite o nome do produto', max_length=30, unique=True, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, help_text='Quantidade do produto', max_digits=5, verbose_name='Quantidade'),
        ),
    ]
