# Generated by Django 6.0.3 on 2026-03-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Fornecedor', max_length=70, verbose_name='Nome')),
                ('cnpj', models.CharField(help_text='CNPJ do fornecedor', max_length=18, unique=True, verbose_name='CNPJ')),
                ('fone', models.CharField(help_text='Fone do fornecedor', max_length=15, verbose_name='Fone')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
    ]
