# Generated by Django 6.0.3 on 2026-05-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(help_text='CNPJ do Fornecedor', max_length=18, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='fone',
            field=models.CharField(help_text='Fone do Fornecedor', max_length=15, verbose_name='Fone'),
        ),
    ]
