# Generated by Django 6.0.3 on 2026-05-04 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_cliente_email_alter_cliente_endereco_and_more'),
        ('funcionarios', '0002_alter_funcionario_email_alter_funcionario_fone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(help_text='Data e hora do atendimento', verbose_name='Horário')),
                ('cliente', models.ForeignKey(help_text='Nome do cliente', on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente', verbose_name='Cliente')),
                ('funcionario', models.ForeignKey(help_text='Nome do funcionario', on_delete=django.db.models.deletion.PROTECT, to='funcionarios.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
            },
        ),
    ]
