# Generated by Django 6.0.3 on 2026-06-01 23:47

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutosServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Quantidade')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos_produto_servico', to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Produto utilizado',
                'verbose_name_plural': 'Produtos utilizados',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do serviço', max_length=100, unique=True, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço do serviço', max_digits=5, verbose_name='Preço')),
                ('descricao', models.CharField(help_text='Descrição do serviço', max_length=300, verbose_name='Descrição do serviço')),
                ('produtos', models.ManyToManyField(related_name='servico_produtos', through='servicos.ProdutosServico', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': [django.db.models.functions.text.Upper('nome')],
            },
        ),
        migrations.AddField(
            model_name='produtosservico',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_servico_servico', to='servicos.servico', verbose_name='Serviço'),
        ),
    ]
