# Generated by Django 6.0.3 on 2026-06-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='produtos',
            field=models.ManyToManyField(related_name='servico_produtos', through='servicos.ProdutosServico', to='produtos.produto'),
        ),
    ]
