# Generated by Django 6.0.3 on 2026-05-04 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_options_remove_produto_name_and_more'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.CharField(help_text='Descrição do serviço', max_length=300, verbose_name='Descrição do serviço'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='nome',
            field=models.CharField(help_text='Nome do serviço', max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.CreateModel(
            name='ProdutosServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Quantidade')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos_produto_servico', to='produtos.produto', verbose_name='Produto')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_servico_servico', to='servicos.servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Produto utilizado',
                'verbose_name_plural': 'Produtos utilizados',
            },
        ),
        migrations.AddField(
            model_name='servico',
            name='produtos',
            field=models.ManyToManyField(related_name='servicos_produtos', through='servicos.ProdutosServico', to='produtos.produto'),
        ),
    ]
