# Generated by Django 6.0.3 on 2026-04-07 16:33

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo', max_length=50, verbose_name='Nome')),
                ('fone', models.CharField(blank=True, help_text='Telefone de contato', max_length=20, verbose_name='Fone')),
                ('email', models.EmailField(blank=True, help_text='Endereço de e-mail', max_length=254, verbose_name='E-mail')),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, help_text='Foto do cliente', null=True, upload_to='Foto', variations={}, verbose_name='Foto')),
                ('endereco', models.CharField(blank=True, help_text='Endereço Completo', max_length=100, verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
